<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Block\Widget\Name;

$viewModel = $block->getData('viewModel');
$status = $viewModel->getCustomerMiStatus();

/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<form class="form form-edit-status"
      action="<?= $block->escapeUrl($block->getUrl('mis/customer/statusPost')) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Status Information')) ?></span></legend><br>
        <div class="field email required" data-container="change-email">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Customer Status')) ?></span></label>
            <div class="control">
                <input type="text" name="status" id="status" autocomplete="status" data-input="change-status"
                       value="<?= $status ?>"
                       title="<?= $block->escapeHtmlAttr(__('Status')) ?>"
                       class="input-text"
                       data-validate="{required:true, 'validate-status':true}" />
            </div>
        </div>
    </fieldset>

        <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $block->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
    </div>
</form>